version: "3.5"

services:
    db:
        container_name: mysqldb
        image: mysql:latest
        restart: unless-stopped
        environment:
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=news_db
            - MYSQL_USER=news_parser
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "5000:3306"
        volumes:
            - ./mysql:/var/lib/mysql

    php:
        container_name: php
        build:
            context: .
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/news_parser
        depends_on:
            - db

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        restart: unless-stopped
        environment:
            - RABBIT_MQ_DEFAULT_USER=guest
            - RABBIT_MQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/news_parser
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
