index:
    path: /
    controller: App\Controller\LoginController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

articles:
    path: /articles
    controller: App\Controller\ArticlesController::index

send_message:
    path: /send-message
    controller: App\Controller\SendNotificationController::sendMessage

logout:
    path: /logout
    methods: GET
