security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            login_throttling: null
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
        secured_area:
            form_login:
                enable_csrf: true

    access_control:
        - { path: ^/articles, roles: [ROLE_ADMINISTRATOR, ROLE_MODERATOR] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
